#ifndef STATE_MACHINE_H__
#define STATE_MACHINE_H__

typedef enum
{   
    TUTORFISH_HOME,
    TUTORFISH_SUBMIT_QUESTION,
    TUTORFISH_SETTINGS,
    CONNECT_TO_WIFI,
    TUTORFISH_VALIDATE_SESSION,
    TUTORFISH_CAPTURE_PIC,
    TUTORFISH_POLL_DB,
    TUTORFISH_DOWNLOAD_TTS,
    TUTORFISH_PLAYBACK_ANSWER,
    TUTORFISH_SUBMIT_QUESTION_COMPLETE,
    TUTORFISH_PIC_ISSUE
} state_machine_t;

extern state_machine_t state_machine;

#endif //STATE_MACHINE_H__